services:
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d 
      - ./mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test 
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
volumes:
  db-store: